name: oracoes_respondidas
description: Um aplicativo para registrar e acompanhar orações respondidas
version: 1.0.0+1
author: Candido H Tominaga
homepage: https://github.com/candidohtominaga/oracoes_respondidas

environment:
  sdk: '>=3.1.5 <4.0.0'

publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  share_plus: ^7.1.0
  flutter_markdown: ^0.6.18
  provider: ^6.1.1
  path_provider: ^2.1.2
  file_picker: 6.1.1
  shared_preferences: ^2.2.2
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
